Password from stdin
tpm2-software/tpm2-totp pull request #89
Opened 2021-07-17 17:28 UTC by EvilBit

fixes #86

At the moment, this forbids `\0` in input stream, but allows `\n`, etc. Not sure if we want to restrict `--password` to single-line, printable ASCII only, or arbitrary binary secrets (and what about `\0` in that case).

2021-07-22 08:51 UTC, diabonas requested changes
LGTM! Could you rebase to include 8cf5b58397f7fb10695679492a37c990cab5d167 ("test: should not recover secret with incorrect password") into b2500a634a7160d8fc3fd04aa90f85aff9e6263f ("feat: read password from stdin"), please? This will make future bisects easier because you don't have to deal with transient CI failures (in this case [from scan-build](https://github.com/tpm2-software/tpm2-totp/runs/3093934476)).

2021-07-22 16:59 UTC, EvilBit commented
> LGTM! Could you rebase to include [8cf5b58](https://github.com/tpm2-software/tpm2-totp/commit/8cf5b58397f7fb10695679492a37c990cab5d167) ("test: should not recover secret with incorrect password") into [b2500a6](https://github.com/tpm2-software/tpm2-totp/commit/b2500a634a7160d8fc3fd04aa90f85aff9e6263f) ("feat: read password from stdin"), please? This will make future bisects easier because you don't have to deal with transient CI failures (in this case [from scan-build](https://github.com/tpm2-software/tpm2-totp/runs/3093934476)).

Sure. But I believe you meant `c9cbceb fix: close potential memory leak in reading from stdin`, not `8cf5b58 test: should not recover secret with incorrect password`?

2021-07-22 17:28 UTC, diabonas commented
> Sure. But I believe you meant `c9cbceb fix: close potential memory leak in reading from stdin`, not `8cf5b58 test: should not recover secret with incorrect password`?

Oops, you are right, I meant to squash c9cbcebc191ca5701204d0dcfd53f7cffd514b92 into b2500a634a7160d8fc3fd04aa90f85aff9e6263f. Also please rebase onto the current master to resolve the conflict after merging #88 :)

2021-07-22 17:55 UTC, EvilBit commented
> Also please rebase onto the current master to resolve the conflict after merging #88 :)

Sure ;)
I knew that would eventually be necessary when submitting multiple PRs simultaneously, but I wanted to develop all features independently based on current `master`, in case one wouldn't be accepted upstream.

If you know of a nicer way to manage this kind of situation, please let me know. :)

2021-07-23 11:58 UTC, diabonas approved these changes
> If you know of a nicer way to manage this kind of situation, please let me know. :)

Not really, unfortunately - I usually base on the current master and rebase if necessary as well

2021-07-23 11:58 UTC, merged